name: Greythr Sign Out Test

on:
  schedule:
    - cron: '30 13 * * 1-5'  # Weekdays at 7:00 PM IST (1:30 PM UTC)
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Verify Cypress version
        run: npx cypress --version

      - name: Run Greythr Sign Out Test
        run: npx cypress run --spec "cypress/e2e/tests/GreythrSignoutTest.cy.ts"
        env:
          NODE_OPTIONS: "--loader ts-node/esm"
